questions = [
    "What are the top tourist places to visit in India?",
    "What is special about Jaipur?",
    "Which are the best places to visit in Kerala?",
    "What are the must-see attractions in Delhi?",
    "Tell me about the beaches of Goa.",
    "What makes Varanasi a unique travel destination?",
    "Which hill stations are best to visit in summer in India?",
    "What is the best time to visit Rajasthan?",
    "What are the major attractions in Mumbai?",
    "Can you suggest some offbeat destinations in India?",
    "Why is Ladakh famous?",
    "Which are the best places for adventure tourism in India?",
    "What is the significance of the Taj Mahal?",
    "Where can I experience snowfall in India?",
    "What are the best cultural festivals to attend in India?",
    "Which Indian city is known as the 'City of Lakes'?",
    "What are the top attractions in Himachal Pradesh?",
    "Which wildlife sanctuaries are best for spotting tigers in India?",
    "Where can I go for the best trekking experiences in India?",
    "What are the best romantic destinations for couples in India?",
    "Which are the best road trips to take in India?",
    "What is famous about Rishikesh and Haridwar?",
    "Which places in India are great for spiritual tourism?",
    "What are the must-visit places in Tamil Nadu?",
    "Where can I experience authentic Rajasthani culture?",
    "What are the best places to visit in North East India?",
    "Can you suggest historical places to visit in India?",
    "Which Indian states are best known for their cuisine?",
    "Where can I experience the best Ayurveda treatments in India?",
    "What are the best places to visit in India for a honeymoon?",
    "What is special about the backwaters of Kerala?",
    "What are the most scenic train journeys in India?",
    "Which Indian cities are best for shopping?",
    "Can you suggest family-friendly vacation spots in India?",
    "What are the best places to visit in Gujarat?",
    "Where can I go for desert tourism in India?",
    "What is the best time to visit Manali?",
    "What are the must-visit temples in India?",
    "Which places in India are best for wildlife photography?",
    "What is the significance of the Golden Temple in Amritsar?",
    "What are the top pilgrimage destinations in India?",
    "Can you suggest eco-tourism destinations in India?",
    "What are the best museums to visit in India?",
    "What is special about Darjeeling?",
    "Where can I enjoy the best street food in India?",
    "What are the must-see places in Andaman and Nicobar Islands?",
    "Which places in India are best for scuba diving and snorkeling?",
    "What is famous about the Sundarbans?",
    "Which are the best national parks in India for wildlife safaris?",
    "What are the best locations in India for solo travelers?",
    "What are the best places to visit in Karnataka?",
    "Which is the best season to visit Meghalaya?",
    "What makes Kolkata a special destination?",
    "Can you suggest the best hill stations in India?",
    "What are the best weekend getaways from Delhi?",
    "Where can I experience India’s best cultural heritage sites?",
    "What are the best food destinations in India?",
    "What is the best time to visit the Valley of Flowers?",
    "What are the famous caves to explore in India?",
    "Which places in India are best for stargazing?",
    "What are the best monsoon destinations in India?",
    "Where can I find the best adventure sports in India?",
    "What are the must-visit UNESCO World Heritage Sites in India?",
    "Which places in India offer the best yoga retreats?",
    "What are the top luxury resorts in India?",
    "What are the best train journeys for tourists in India?",
    "Which are the best cycling routes in India?",
    "What are the most haunted places in India?",
    "Where can I go for the best river rafting in India?",
    "What are the top winter destinations in India?",
    "Which beaches in India are best for water sports?",
    "Where can I enjoy the best local festivals in India?",
    "What are the best honeymoon destinations in India?",
    "What is unique about Pondicherry?",
    "Where can I find the best street shopping in India?",
    "What are the best historical forts to visit in India?",
    "What is special about the Rann of Kutch?",
    "Which Indian cities are best for nightlife?",
    "What are the best places in India for camping?",
    "Where can I experience traditional village life in India?",
    "What are the top eco-friendly destinations in India?",
    "Which places in India are best for bird watching?",
    "What are the best places in India to see waterfalls?",
    "Where can I visit hot springs in India?",
    "What are the best unexplored islands in India?",
    "Which Indian cities are best for photography?",
    "Where can I find the best local handicrafts in India?",
    "What are the best places for snorkeling in India?",
    "What are the most beautiful sunrise and sunset points in India?",
    "What is special about Spiti Valley?",
    "Where can I experience cherry blossom season in India?",
    "Which hill stations in India receive snowfall?",
    "Where can I visit floating markets in India?",
    "What are the top Buddhist monasteries to visit in India?",
    "What is special about Gokarna?",
    "Which places in India have the best mountain views?",
    "What are the best jungle resorts in India?",
    "Where can I enjoy authentic tribal tourism in India?",
    "What are the best places to see sand dunes in India?",
    "What are the best luxury train journeys in India?",
    "What are the best places to visit in Andhra Pradesh?",
    "Tell me about the historical significance of Hampi.",
    "What are the best places to visit in Chhattisgarh?",
    "What are the best places to visit in Haryana?",
    "What are the best places to visit in Jharkhand?",
    "What are the best places to visit in Manipur?",
    "What are the best places to visit in Mizoram?",
    "What are the best places to visit in Nagaland?",
    "What are the best places to visit in Odisha?",
    "What are the best places to visit in Punjab?",
    "What are the best places to visit in Sikkim?",
    "What are the best places to visit in Telangana?",
    "What are the best places to visit in Tripura?",
    "What are the best places to visit in Uttarakhand?",
    "What are the best places to visit in West Bengal?",
    "What are the best places to visit in Puducherry?",
    "What are the best places to visit in Chandigarh?",
    "What are the best places to visit in Lakshadweep?",
    "What are the best places to visit in Daman and Diu?",
    "What are the best places to visit in Dadra and Nagar Haveli?",
    "What is the history of Hyderabad's Charminar?",
    "What are the best street food options in Lucknow?",
    "What are the best museums in Chennai?",
    "What are the best places to see tea plantations in Assam?",
    "What are the best places to visit in Coorg?",
    "What are the best places to see coffee plantations in India?",
    "What are the best places to see spice plantations in India?",
    "What are the best places to visit in Kutch during Rann Utsav?",
    "Where can I find the best silk sarees in India?",
    "What are the best places to visit in Madurai?",
    "Where can I learn traditional Indian pottery?",
    "Where can I learn traditional Indian weaving?",
    "Where can I learn traditional Indian cooking?",
    "Where can I learn traditional Indian music?",
    "Where can I learn traditional Indian dance?",
    "Where can I participate in a local village festival in India?",
    "Where can I learn about Indian astronomy?",
    "Where can I learn about Indian mythology?",
    "Where can I learn about Indian philosophy?",
    "Where can I find the best places for birdwatching in the Himalayas?",
    "Where can I find the best places for white water rafting in the Ganges?",
    "Where can I find the best places for paragliding in India?",
    "Where can I find the best places for rock climbing in India?",
    "Where can I find the best places for skiing in India?",
    "Where can I find the best places for snowboarding in India?",
    "Where can I find the best places for ice skating in India?",
    "Where can I find the best places for hot air ballooning in India?",
    "Where can I find the best places for camel safaris in India?",
    "Where can I find the best places for elephant safaris in India?",
    "Where can I find the best places for jeep safaris in India?",
    "What are the best places for a photography tour in India?",
    "What are the best places for a food tour in India?",
    "What are the best places for a heritage walk in India?",
    "What are the best places for a spiritual retreat in India?",
    "What are the best places for a wellness retreat in India?",
    "What are the best places for a yoga and meditation retreat in India?",
    "What are the best places for an art and craft workshop in India?",
    "What are the best places for a wildlife photography workshop in India?",
    "What are the best places for a cooking workshop in India?",
    "What are the best places for a language learning program in India?",
    "Where can I find the best places for sustainable tourism in India?",
    "Where can I find the best places for community-based tourism in India?",
    "Where can I find the best places for homestays in India?",
    "Where can I find the best places for farm stays in India?",
    "Where can I find the best places for eco-lodges in India?",
    "What are the best places for a volunteer vacation in India?",
    "What are the best places for a student exchange program in India?",
    "What are the best places for a gap year in India?",
    "What are the best places for a digital nomad in India?",
    "What are the best places for a long-term stay in India?",
    "Where can I find the best places for a destination wedding in India?",
    "Where can I find the best places for a pre-wedding photoshoot in India?",
    "What are the best places for a corporate retreat in India?",
    "What are the best places for a team-building activity in India?",
    "What are the best places for a conference in India?",
    "What are the best places for a trade show in India?",
    "What are the best places for a music festival in India?",
    "What are the best places for a dance festival in India?",
    "What are the best places for a film festival in India?",
    "What are the best places for a literature festival in India?",
    "What are the top tourist places to visit in Europe?",
    "What is special about Paris?",
    "Which are the best places to visit in Italy?",
    "What are the must-see attractions in London?",
    "Tell me about the beaches of Thailand.",
    "What makes Tokyo a unique travel destination?",
    "Which mountain ranges are best to visit in Switzerland?",
    "What is the best time to visit Japan?",
    "What are the major attractions in New York City?",
    "Can you suggest some offbeat destinations in Southeast Asia?",
    "Why is Iceland famous?",
    "Which are the best places for adventure tourism in South America?",
    "What is the significance of the Great Wall of China?",
    "Where can I experience the Northern Lights?",
    "What are the best cultural festivals to attend in Mexico?",
    "Which city is known as the 'City of Lights'?",
    "What are the top attractions in Australia?",
    "Which wildlife sanctuaries are best for spotting lions in Africa?",
    "Where can I go for the best trekking experiences in Nepal?",
    "What are the best romantic destinations for couples in Bali?",
    "Which are the best road trips to take in New Zealand?",
    "What is famous about the Amazon rainforest?",
    "Which places are great for spiritual tourism in Tibet?",
    "What are the must-visit places in Egypt?",
    "Where can I experience authentic Italian cuisine?",
    "What are the best places to visit in Canada?",
    "Can you suggest historical places to visit in Greece?",
    "What are the best places to visit in Arunachal Pradesh?",
    "Where can I experience the best traditional folk dances in India?",
    "What are the best places to visit in Bihar for history lovers?",
    "Which Indian cities have the best Christmas celebrations?",
    "Where can I experience the best tribal festivals in India?",
    "What are the best locations for camping near rivers in India?",
    "Which caves in India are famous for ancient paintings?",
    "Where can I experience the best sunrise views in India?",
    "What are the best places to visit in Madhya Pradesh for nature lovers?",
    "Which hill stations in India are best for snowfall?",
    "What are the best places to visit in Maharashtra beyond Mumbai?",
    "Where can I experience the best local markets in Rajasthan?",
    "What are the best places in India to witness a sandstorm?",
    "Where can I explore the most scenic valleys in India?",
    "Which forts in India offer the best panoramic views?",
    "Where can I experience the best stargazing in Rajasthan?",
    "What are the best places to visit in India during Holi?",
    "Where can I find the best local pottery workshops in India?",
    "What are the best places in India for a solo backpacking trip?",
    "Which Indian cities are best for exploring colonial architecture?",
    "Where can I visit the oldest temples in India?",
    "What are the best places to enjoy cherry blossoms in India?",
    "Where can I experience rural life and organic farming in India?",
    "What are the best places in India for a digital detox vacation?",
    "Which Indian wildlife sanctuaries are best for spotting leopards?",
    "Where can I experience the best boat festivals in India?",
    "What are the best places in India for a monsoon trek?",
    "Where can I find the most scenic railway stations in India?",
    "What are the best food streets to explore in Hyderabad?",
    "Where can I visit the best ancient stepwells in India?",
    "What are the best museums to visit in Kolkata?",
    "Which are the best unexplored islands in India?",
    "Where can I experience the best paragliding in Himachal Pradesh?",
    "What are the most haunted forts and palaces in India?",
    "Where can I go for the best horse safaris in Rajasthan?",
    "What are the best waterfalls to visit in Karnataka?",
    "Where can I experience the best night safaris in India?",
    "What are the best places to witness elephant processions in India?",
    "Where can I visit the best hidden beaches in Kerala?",
    "Which are the best offbeat tea estates to visit in India?",
    "Where can I explore the best coffee plantations in South India?",
    "What are the best scenic mountain roads for bike trips in India?",
    "Where can I experience the best homestays with local families in India?",
    "What are the best places to visit in India for eco-tourism?",
    "Where can I go for the best rock climbing experiences in India?",
    "Which places in India are best for kayaking and canoeing?",
    "Where can I explore India's best coral reefs for snorkeling?",
    "What are the best birdwatching destinations in South India?",
    "Which are the best salt flats to visit in India apart from the Rann of Kutch?",
    "Where can I experience a camel festival in India?",
]


set_questions = set(questions)
print(len(set_questions))

print(len(questions))